export const typeColors: Record<string, string> = {
  normal: 'pokemon-type-normal',
  fire: 'pokemon-type-fire',
  water: 'pokemon-type-water',
  electric: 'pokemon-type-electric',
  grass: 'pokemon-type-grass',
  ice: 'pokemon-type-ice',
  fighting: 'pokemon-type-fighting',
  poison: 'pokemon-type-poison',
  ground: 'pokemon-type-ground',
  flying: 'pokemon-type-flying',
  psychic: 'pokemon-type-psychic',
  bug: 'pokemon-type-bug',
  rock: 'pokemon-type-rock',
  ghost: 'pokemon-type-ghost',
  dragon: 'pokemon-type-dragon',
  dark: 'pokemon-type-dark',
  steel: 'pokemon-type-steel',
  fairy: 'pokemon-type-fairy',
};
